version: '2.0'

services:
  node:
    image: ghcr.io/foundry-rs/foundry:latest
    command:
      - anvil --block-time=1 --block-base-fee-per-gas 0 --host=0.0.0.0 --disable-block-gas-limit --gas-price 0
    ports:
      - "8545:8545"
    volumes:
      - anvil-data:/var/anvil/data
    restart: always

volumes:
  anvil-data:
